services:


  mysql:
    image: mysql:5.7
    container_name: jms_mysql
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin'] 
    volumes:
      - ${volume_loc}/volume/mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-file: 7
        max-size: 50m

  redis:
    image: redis:6.2
    container_name: jms_redis
    restart: always
    network_mode: host
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: >
      sh -c "exec redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - ${volume_loc}/volume/redis_data:/data
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-file: 7
        max-size: 50m



  jms:
    image: kkasd92/jms_all_repack:latest 
    container_name: jms_all
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - redis
    privileged: true
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_ENGINE: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: ${REDIS_PORT}
      SECRET_KEY: ${SECRET_KEY}
      BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN}
      LOG_LEVEL: ERROR
      DOMAINS: ${DOMAINS}
      GUNICORN_CMD_ARGS: "--forwarded-allow-ips=*"
    volumes:
      - ${volume_loc}/volume/jumpserver/core/data:/opt/jumpserver/data
      - ${volume_loc}/volume/jumpserver/koko/data:/opt/koko/data
      - ${volume_loc}/volume/jumpserver/lion/data:/opt/lion/data
      - ${volume_loc}/volume/jumpserver/kael/data:/opt/kael/data
      - ${volume_loc}/volume/jumpserver/chen/data:/opt/chen/data
      - ${volume_loc}/volume/jumpserver/web/log:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - ${volume_loc}/volume/jumpserver/nginx/etc/http_server.conf:/etc/nginx/conf.d/http_server.conf
      - ${volume_loc}/volume/jumpserver/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-file: 7
        max-size: 50m





  nginx:
    image: gaciaga/nginx-vts:latest
    container_name: nginx
    volumes:
      - ${volume_loc}/volume/nginx/etc/:/etc/nginx/
      - ${volume_loc}/volume/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on: 
      - jms
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10k



  vnc:
    container_name: vnc_brows
    image: elestio/docker-desktop-vnc
    ports: 
      - 5900:5900
    environment:
      - VNC_PASSWORD=1qaz@WSX3edc
      - RESOLUTION=1920x1080
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10k


  vnc2:
    container_name: vnc_brows2
    image: elestio/docker-desktop-vnc
    ports:
      - 5901:5900
    environment:
      - VNC_PASSWORD=1qaz@WSX3edc
      - RESOLUTION=1920x1080
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10k
